services:
  mongo:
    image: mongo:4.4
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${ME_CONFIG_MONGODB_HOST}:3001"
    env_file:
      - .env

  # pgadmin:
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PGADMIN_DEFAULT_PORT}:80"
  #   depends_on:
  #     - postgres

volumes:
  mongo-data:
